apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: vanguardmain
  namespace: vanguard-main
spec:
  host: lvopenapidev.com
  upstreams:
  - name: gw
    service: openapi-gateway-service
    port: 80
  subroutes:
  - path: /vanguard/main/gateway
    action:
      pass: gw