apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: teamsemain
  namespace: teamse-main
spec:
  host: lvopenapidev.com
  upstreams:
  - name: gw
    service: openapi-gateway-service
    port: 80
  subroutes:
  - path: /teamse/main/gateway
    action:
      pass: gw