apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: team360main
  namespace: team360-main
spec:
  host: lvopenapidev.com
  upstreams:
  - name: gw
    service: openapi-gateway-service
    port: 80
  subroutes:
  - path: /team360/main/gateway
    action:
      pass: gw