apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: gammadevelop
  namespace: gamma-develop
spec:
  host: lvopenapidev.com
  upstreams:
  - name: gw
    service: openapi-gateway-service
    port: 80
  subroutes:
  - path: /gamma/develop/gateway
    action:
      pass: gw