name: Create OpenAPI PRs on release

on:
  # push:
  #    branches:
       # - main 
    #    - 'hotfix/PRcreate'
    #  paths:
    #    - 'resources/**'
  
  workflow_dispatch:
  
jobs:
  create-PRs:
    name: Create PRs for OpenAPI
    runs-on: ubuntu-latest
    steps:

    - name: vsg_openapi_gateway
      uses: emiliopedrollo/create-pull-request@v2.0.0
      continue-on-error: true
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_gateway
        # A comma or newline separated list of labels
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_application
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_application
        # A comma or newline separated list of labels
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_settings
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
      # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_settings
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_nexus
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_nexus
        # A comma or newline separated list of labels
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_lead
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_lead
        # A comma or newline separated list of labels
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_documents
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_documents
        # A comma or newline separated list of labels
        reviewers: ISakalievVSG

    - name: vsg_openapi_api_decision
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_decision
        # A comma or newline separated list of labels      
        reviewers: ISakalievVSG
       
    - name: vsg_openapi_api_composer
      continue-on-error: true
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: ${{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge develop into main  ${{ github.run_number}}
        head: develop
        # The Pull Request base branch
        base: main
        # The owner and repository
        repository: jkhy/vsg_openapi_api_composer
        # A comma or newline separated list of labels      
        reviewers: ISakalievVSG
