name: Create OpenAPI PRs on release

on:
  push:
     branches:
       # - main 
       - 'hotfix/PRcreate'
     paths:
       - 'resources/**'
  
  workflow_dispatch:
  
jobs:
  create-PRs:
    name: Create PRs for OpenAPI
    runs-on: ubuntu-latest
    steps:
 
    # - name: Trigger workflow
    # # You may pin to the exact commit or the version.
    # # uses: dusansimic/trigger-workflow-action@8b004e8247e9d2e7354366bd128160d7e78b47c8
    #   uses: dusansimic/trigger-workflow-action@v0.1.0
    #   with:
    #     # The GitHub token used to trigger workflow
    #     # github-token: # optional, default is ${{ github.token }}
    #     # Workflow name to be triggered (the name of the file)
    #     name: .github/workflows/delete-old-images.yml
    #     # Owner of the repository that contains the workflow (username or org. name)
    #     owner: jkhy
    #     # Name of the repository
    #     repo: vsg_LoanVantage
    #     ref: master
    #     debug: true
    - name: Creates Pull Request
  # You may pin to the exact commit or the version.
  # uses: emiliopedrollo/create-pull-request@f7934fae6d59ce93ecc17824f1c69659fe3f2c22
      uses: emiliopedrollo/create-pull-request@v2.0.0
      with:
        # A token that can be used to authenticate within GitHub with content write access to your repo
        token: {{ secrets.PRsecret }}
        # The title of the Pull Request
        title: Merge main into support

        head: main
        # The Pull Request base branch
        base: support
        # The owner and repository
        repository: jkhy/vsg_openapi_gateway
        # A comma or newline separated list of labels

        reviewers: ISakalievVSG

            
